// Restored from ref/webview/assets/_basePickBy-X1_M8KZ0.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 11 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const basePickByA: any;
export declare const basePickByC: any;
export declare const basePickByD: any;
export declare const basePickByI: any;
export declare const basePickByL: any;
export declare const basePickByN: any;
export declare const basePickByO: any;
export declare const basePickByR: any;
export declare const basePickByS: any;
export declare const basePickByT: any;
export declare const basePickByU: any;
