// Restored from ref/webview/assets/main-BDm-p1LA.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 11 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const mainA: any;
export declare const mainC: any;
export declare const mainD: any;
export declare const mainI: any;
export declare const mainL: any;
export declare const mainN: any;
export declare const mainO: any;
export declare const mainR: any;
export declare const mainS: any;
export declare const mainT: any;
export declare const mainU: any;
