// Restored from ref/webview/assets/dist-uq8yzYFr.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 17 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const _: any;
export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const distA: any;
export declare const distC: any;
export declare const distD: any;
export declare const distF: any;
export declare const distG: any;
export declare const distH: any;
export declare const distI: any;
export declare const distL: any;
export declare const distM: any;
export declare const distN: any;
export declare const distO: any;
export declare const distP: any;
export declare const distR: any;
export declare const distS: any;
export declare const distT: any;
export declare const distU: any;
export declare const distUnderscore: any;
