// Restored from ref/webview/assets/chunk-Cq_f4orQ.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 7 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const i: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkA: any;
export declare const chunkI: any;
export declare const chunkN: any;
export declare const chunkO: any;
export declare const chunkR: any;
export declare const chunkS: any;
export declare const chunkT: any;
