// Restored from ref/webview/assets/chunk-YZCP3GAM-CkcPUeYE.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 8 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const i: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkYZCP3GAMA: any;
export declare const chunkYZCP3GAMC: any;
export declare const chunkYZCP3GAMI: any;
export declare const chunkYZCP3GAMN: any;
export declare const chunkYZCP3GAMO: any;
export declare const chunkYZCP3GAMR: any;
export declare const chunkYZCP3GAMS: any;
export declare const chunkYZCP3GAMT: any;

// Additional aliases exported for consumers mapped via IMPORT_MAP
export const drawRect: any = undefined;
export const drawBackgroundRect: any = undefined;
export const drawText: any = undefined;
export const drawImage: any = undefined;
export const drawEmbeddedImage: any = undefined;
export const getNoteRectDefaults: any = undefined;
export const getTextObjDefaults: any = undefined;
export const createTooltip: any = undefined;
