// Restored from ref/webview/assets/chunk-CVBHYZKI-D5c0MJ_k.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 1 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkCVBHYZKI: any;

// Additional aliases exported for consumers mapped via IMPORT_MAP
export const getSubGraphTitleMargins: any = undefined;
