// Restored from ref/webview/assets/chunk-TZMSLE5B-BvWo7845.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 7 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const i: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkTZMSLE5BA: any;
export declare const chunkTZMSLE5BI: any;
export declare const chunkTZMSLE5BN: any;
export declare const chunkTZMSLE5BO: any;
export declare const chunkTZMSLE5BR: any;
export declare const chunkTZMSLE5BS: any;
export declare const chunkTZMSLE5BT: any;
