// Restored from ref/webview/assets/chunk-K5T4RW27-1QwNQQi0.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 18 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const _: any;
export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
export declare const v: any;

// Aliases used by consumer checkpoints
export declare const chunkK5T4RW27A: any;
export declare const chunkK5T4RW27C: any;
export declare const chunkK5T4RW27D: any;
export declare const chunkK5T4RW27F: any;
export declare const chunkK5T4RW27G: any;
export declare const chunkK5T4RW27H: any;
export declare const chunkK5T4RW27I: any;
export declare const chunkK5T4RW27L: any;
export declare const chunkK5T4RW27M: any;
export declare const chunkK5T4RW27N: any;
export declare const chunkK5T4RW27O: any;
export declare const chunkK5T4RW27P: any;
export declare const chunkK5T4RW27R: any;
export declare const chunkK5T4RW27S: any;
export declare const chunkK5T4RW27T: any;
export declare const chunkK5T4RW27U: any;
export declare const chunkK5T4RW27Underscore: any;
export declare const chunkK5T4RW27V: any;
