// Restored from ref/webview/assets/markdown-to-search-text-D4gbAqkt.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 12 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const markdownToSearchTextA: any;
export declare const markdownToSearchTextC: any;
export declare const markdownToSearchTextD: any;
export declare const markdownToSearchTextF: any;
export declare const markdownToSearchTextI: any;
export declare const markdownToSearchTextL: any;
export declare const markdownToSearchTextN: any;
export declare const markdownToSearchTextO: any;
export declare const markdownToSearchTextR: any;
export declare const markdownToSearchTextS: any;
export declare const markdownToSearchTextT: any;
export declare const markdownToSearchTextU: any;
