// Restored from ref/webview/assets/chunk-JA3XYJ7Z-CjR9BG5n.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 6 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const chunkJA3XYJ7ZA: any;
export declare const chunkJA3XYJ7ZI: any;
export declare const chunkJA3XYJ7ZN: any;
export declare const chunkJA3XYJ7ZO: any;
export declare const chunkJA3XYJ7ZR: any;
export declare const chunkJA3XYJ7ZT: any;
