// Restored from ref/webview/assets/metric-helpers-BidZZeRm.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 12 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const metricHelpersA: any;
export declare const metricHelpersC: any;
export declare const metricHelpersD: any;
export declare const metricHelpersF: any;
export declare const metricHelpersI: any;
export declare const metricHelpersL: any;
export declare const metricHelpersN: any;
export declare const metricHelpersO: any;
export declare const metricHelpersR: any;
export declare const metricHelpersS: any;
export declare const metricHelpersT: any;
export declare const metricHelpersU: any;
