// Restored from ref/webview/assets/pdf-c2WnNMiD.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 56 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const AbortException: any;
export declare const AnnotationEditorLayer: any;
export declare const AnnotationEditorParamsType: any;
export declare const AnnotationEditorType: any;
export declare const AnnotationEditorUIManager: any;
export declare const AnnotationLayer: any;
export declare const AnnotationMode: any;
export declare const AnnotationType: any;
export declare const CSSConstants: any;
export declare const ColorPicker: any;
export declare const DOMSVGFactory: any;
export declare const DrawLayer: any;
export declare const FeatureTest: any;
export declare const GlobalWorkerOptions: any;
export declare const ImageKind: any;
export declare const InvalidPDFException: any;
export declare const MathClamp: any;
export declare const OPS: any;
export declare const OutputScale: any;
export declare const PDFDataRangeTransport: any;
export declare const PDFDateString: any;
export declare const PDFWorker: any;
export declare const PasswordResponses: any;
export declare const PermissionFlag: any;
export declare const PixelsPerInch: any;
export declare const RenderingCancelledException: any;
export declare const ResponseException: any;
export declare const SignatureExtractor: any;
export declare const SupportedImageMimeTypes: any;
export declare const TextLayer: any;
export declare const TouchManager: any;
export declare const Util: any;
export declare const VerbosityLevel: any;
export declare const XfaLayer: any;
export declare const applyOpacity: any;
export declare const build: any;
export declare const createValidAbsoluteUrl: any;
export declare const fetchData: any;
export declare const findContrastColor: any;
export declare const getDocument: any;
export declare const getFilenameFromUrl: any;
export declare const getPdfFilenameFromUrl: any;
export declare const getRGB: any;
export declare const getUuid: any;
export declare const getXfaPageViewport: any;
export declare const isDataScheme: any;
export declare const isPdfFile: any;
export declare const isValidExplicitDest: any;
export declare const noContextMenu: any;
export declare const normalizeUnicode: any;
export declare const renderRichText: any;
export declare const setLayerDimensions: any;
export declare const shadow: any;
export declare const stopEvent: any;
export declare const updateUrlHash: any;
export declare const version: any;
