// Restored from ref/webview/assets/pkg-CJtlEP_l.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 16 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const Analytics: any;
export declare const Context: any;
export declare const ContextCancelation: any;
export declare const EventFactory: any;
export declare const Group: any;
export declare const UniversalStorage: any;
export declare const User: any;
export declare const getGlobalAnalytics: any;
export declare const isDestinationPluginWithAddMiddleware: any;
export declare const pkgAnalyticsBrowser: any;
export declare const pkgAnalyticsNode: any;
export declare const resolveAliasArguments: any;
export declare const resolveArguments: any;
export declare const resolvePageArguments: any;
export declare const resolveUserArguments: any;
export declare const segmentio: any;
