// Restored from ref/webview/assets/use-auth-pK1tONyf.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 9 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const useAuthA: any;
export declare const useAuthC: any;
export declare const useAuthI: any;
export declare const useAuthL: any;
export declare const useAuthN: any;
export declare const useAuthO: any;
export declare const useAuthR: any;
export declare const useAuthS: any;
export declare const useAuthT: any;
