// Restored from ref/webview/assets/workbook-from-markdown-Do0YNaaN.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 2 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const workbookFromMarkdownBuildTableValuesFromMarkdown: any;
export declare const workbookFromMarkdownSanitizeSheetName: any;
