// Restored from ref/webview/assets/electron-menu-shortcuts-j6UKqTX5.js
// Webview command definitions.

import type { CommandDefinition } from "./types";

/** Webview commands (available in the main Codex UI). */
export const webviewCommands: CommandDefinition[] = [
  {
    id: "newThread",
    titleIntlId: "codex.command.newThread",
    descriptionIntlId: "codex.commandDescription.newThread",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: {
      menuTitle: "New Chat",
      menuTitleIntlId: "codex.commandMenuTitle.newThread",
      defaultKeybindings: [
        { key: "CmdOrCtrl+N" },
        { key: "CmdOrCtrl+Shift+O" },
      ],
    },
    vscodeCommand: {
      commandId: "chatgpt.newChat",
      title: "New Thread in Codex Sidebar",
      keybinding: {
        key: "ctrl+n",
        mac: "cmd+n",
        when: "chatgpt.supportsNewChatKeyShortcut",
      },
    },
  },
  {
    id: "quickChat",
    titleIntlId: "codex.command.quickChat",
    descriptionIntlId: "codex.commandDescription.quickChat",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: {
      menuTitle: "Quick Chat",
      menuTitleIntlId: "codex.commandMenuTitle.quickChat",
      defaultKeybindings: [{ key: "CmdOrCtrl+Alt+N" }],
    },
  },
  {
    id: "openThreadInNewWindow",
    titleIntlId: "codex.command.openThreadInNewWindow",
    descriptionIntlId: "codex.commandDescription.openThreadInNewWindow",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: {
      menuTitle: "Open in New Window",
      menuTitleIntlId: "codex.commandMenuTitle.openThreadInNewWindow",
    },
  },
  {
    id: "archiveThread",
    titleIntlId: "codex.command.archiveThread",
    descriptionIntlId: "codex.commandDescription.archiveThread",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: {
      menuTitle: "Archive chat",
      menuTitleIntlId: "codex.commandMenuTitle.archiveThread",
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+A" }],
    },
  },
  {
    id: "toggleThreadPin",
    titleIntlId: "codex.command.toggleThreadPin",
    descriptionIntlId: "codex.commandDescription.toggleThreadPin",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: {
      menuTitle: "Pin/unpin chat",
      menuTitleIntlId: "codex.commandMenuTitle.toggleThreadPin",
      defaultKeybindings: [{ key: "CmdOrCtrl+Alt+P" }],
    },
  },
  {
    id: "copyConversationMarkdown",
    titleIntlId: "codex.command.copyConversationMarkdown",
    descriptionIntlId: "codex.commandDescription.copyConversationMarkdown",
  },
  {
    id: "openSideChat",
    titleIntlId: "codex.command.openSideChat",
    descriptionIntlId: "codex.commandDescription.openSideChat",
    availableIn: ["electron"],
    shortcutScope: "app",
    commandMenuGroupKey: "thread",
    commandMenu: true,
    electron: { defaultKeybindings: [{ key: "CmdOrCtrl+Alt+S" }] },
  },
  {
    id: "openControlWindow",
    titleIntlId: "codex.command.openControlWindow",
    descriptionIntlId: "codex.commandDescription.openControlWindow",
    commandMenuGroupKey: "app",
    commandMenu: true,
  },
  {
    id: "composer.openModelPicker",
    titleIntlId: "codex.command.composer.openModelPicker",
    descriptionIntlId: "codex.commandDescription.composer.openModelPicker",
    shortcutScope: "app",
    electron: {
      defaultKeybindings: [{ key: "Ctrl+Shift+M" }],
    },
  },
  {
    id: "composer.startVoiceMode",
    titleIntlId: "codex.command.composer.startVoiceMode",
    descriptionIntlId: "codex.commandDescription.composer.startVoiceMode",
    shortcutScope: "app",
    electron: {
      defaultKeybindings: [{ key: "Ctrl+Shift+V" }],
    },
  },
  {
    id: "composer.startDictation",
    titleIntlId: "codex.command.composer.startDictation",
    descriptionIntlId: "codex.commandDescription.composer.startDictation",
    shortcutScope: "app",
    electron: {
      menuTitle: "Dictation",
      menuTitleIntlId: "codex.commandMenuTitle.composer.startDictation",
      defaultKeybindings: [{ key: "Ctrl+Shift+D" }],
    },
  },
  {
    id: "composer.submit",
    titleIntlId: "codex.command.composer.submit",
    descriptionIntlId: "codex.commandDescription.composer.submit",
    shortcutScope: "app",
  },
  {
    id: "composer.toggleFastMode",
    titleIntlId: "codex.command.composer.toggleFastMode",
    descriptionIntlId: "codex.commandDescription.composer.toggleFastMode",
    shortcutScope: "app",
  },
  {
    id: "composer.increaseReasoningEffort",
    titleIntlId: "codex.command.composer.increaseReasoningEffort",
    descriptionIntlId:
      "codex.commandDescription.composer.increaseReasoningEffort",
    shortcutScope: "app",
  },
  {
    id: "composer.decreaseReasoningEffort",
    titleIntlId: "codex.command.composer.decreaseReasoningEffort",
    descriptionIntlId:
      "codex.commandDescription.composer.decreaseReasoningEffort",
    shortcutScope: "app",
  },
  {
    id: "composer.cycleReasoningEffort",
    titleIntlId: "codex.command.composer.cycleReasoningEffort",
    descriptionIntlId: "codex.commandDescription.composer.cycleReasoningEffort",
    shortcutScope: "app",
  },
  {
    id: "composer.togglePlanMode",
    titleIntlId: "codex.command.composer.togglePlanMode",
    descriptionIntlId: "codex.commandDescription.composer.togglePlanMode",
    shortcutScope: "app",
  },
  {
    id: "approval.approve",
    titleIntlId: "codex.command.approval.approve",
    descriptionIntlId: "codex.commandDescription.approval.approve",
    shortcutScope: "app",
    electron: {
      defaultKeybindings: [{ key: "Enter" }],
    },
  },
  {
    id: "approval.decline",
    titleIntlId: "codex.command.approval.decline",
    descriptionIntlId: "codex.commandDescription.approval.decline",
    shortcutScope: "app",
    electron: {
      defaultKeybindings: [{ key: "Escape" }],
    },
  },
  {
    id: "git.commit",
    titleIntlId: "codex.command.git.commit",
    descriptionIntlId: "codex.commandDescription.git.commit",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
    commandMenu: true,
  },
  {
    id: "git.createPullRequest",
    titleIntlId: "codex.command.git.createPullRequest",
    descriptionIntlId: "codex.commandDescription.git.createPullRequest",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
    commandMenu: true,
  },
  {
    id: "forkThread",
    titleIntlId: "codex.command.forkThread",
    descriptionIntlId: "codex.commandDescription.forkThread",
    shortcutScope: "app",
  },
  {
    id: "openAvatarOverlay",
    titleIntlId: "codex.command.openPetOverlay",
    descriptionIntlId: "codex.commandDescription.openPetOverlay",
    commandMenuGroupKey: "app",
    commandMenu: true,
    electron: {
      menuTitle: "Wake Pet",
      menuTitleIntlId: "codex.commandMenuTitle.openAvatarOverlay",
    },
  },
  {
    id: "previousTab",
    titleIntlId: "codex.command.previousTab",
    descriptionIntlId: "codex.commandDescription.previousTab",
    availableIn: ["electron"],
    shortcutScope: "app",
    allowsKeyRepeat: true,
    commandMenuGroupKey: "navigation",
    electron: {
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+[" }],
      platformDefaultKeybindings: {
        macOS: [
          { key: "Ctrl+Shift+Tab" },
          { key: "Command+Shift+[" },
          { key: "Command+Alt+Left" },
        ],
        default: [
          { key: "Ctrl+Shift+Tab" },
          { key: "Ctrl+Shift+[" },
          { key: "Ctrl+PageUp" },
        ],
      },
    },
  },
  {
    id: "previousThread",
    titleIntlId: "codex.command.previousThread",
    descriptionIntlId: "codex.commandDescription.previousThread",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Previous Chat",
      menuTitleIntlId: "codex.commandMenuTitle.previousThread",
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+[" }],
      platformDefaultKeybindings: {
        macOS: [{ key: "Command+Shift+[" }, { key: "Command+Alt+Left" }],
        default: [{ key: "Ctrl+Shift+[" }, { key: "Ctrl+PageUp" }],
      },
    },
  },
  {
    id: "previousRecentThread",
    titleIntlId: "codex.command.previousRecentThread",
    descriptionIntlId: "codex.commandDescription.previousRecentThread",
    availableIn: ["electron"],
    shortcutScope: "app",
    allowsKeyRepeat: true,
    commandMenuGroupKey: "navigation",
    electron: {
      defaultKeybindings: [{ key: "Ctrl+Shift+Tab" }],
    },
  },
  {
    id: "nextTab",
    titleIntlId: "codex.command.nextTab",
    descriptionIntlId: "codex.commandDescription.nextTab",
    availableIn: ["electron"],
    shortcutScope: "app",
    allowsKeyRepeat: true,
    commandMenuGroupKey: "navigation",
    electron: {
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+]" }],
      platformDefaultKeybindings: {
        macOS: [
          { key: "Ctrl+Tab" },
          { key: "Command+Shift+]" },
          { key: "Command+Alt+Right" },
        ],
        default: [
          { key: "Ctrl+Tab" },
          { key: "Ctrl+Shift+]" },
          { key: "Ctrl+PageDown" },
        ],
      },
    },
  },
  {
    id: "nextThread",
    titleIntlId: "codex.command.nextThread",
    descriptionIntlId: "codex.commandDescription.nextThread",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Next Chat",
      menuTitleIntlId: "codex.commandMenuTitle.nextThread",
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+]" }],
      platformDefaultKeybindings: {
        macOS: [{ key: "Command+Shift+]" }, { key: "Command+Alt+Right" }],
        default: [{ key: "Ctrl+Shift+]" }, { key: "Ctrl+PageDown" }],
      },
    },
  },
  {
    id: "nextRecentThread",
    titleIntlId: "codex.command.nextRecentThread",
    descriptionIntlId: "codex.commandDescription.nextRecentThread",
    availableIn: ["electron"],
    shortcutScope: "app",
    allowsKeyRepeat: true,
    commandMenuGroupKey: "navigation",
    electron: {
      defaultKeybindings: [{ key: "Ctrl+Tab" }],
    },
  },
  {
    id: "switchToMode1",
    titleIntlId: "codex.command.switchToMode1",
    descriptionIntlId: "codex.commandDescription.switchToMode1",
    availableIn: ["electron"],
    shortcutScope: "app",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      platformDefaultKeybindings: {
        macOS: [{ key: "Ctrl+1" }],
        default: [{ key: "Alt+1" }],
      },
    },
  },
  {
    id: "switchToMode2",
    titleIntlId: "codex.command.switchToMode2",
    descriptionIntlId: "codex.commandDescription.switchToMode2",
    availableIn: ["electron"],
    shortcutScope: "app",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      platformDefaultKeybindings: {
        macOS: [{ key: "Ctrl+2" }],
        default: [{ key: "Alt+2" }],
      },
    },
  },
  {
    id: "settings",
    titleIntlId: "codex.command.settings",
    descriptionIntlId: "codex.commandDescription.settings",
    commandMenuGroupKey: "app",
    commandMenu: true,
    electron: {
      menuTitle: "Settings…",
      menuTitleIntlId: "codex.commandMenuTitle.settings",
      defaultKeybindings: [{ key: "CmdOrCtrl+," }],
    },
  },
  {
    id: "mcpSettings",
    titleIntlId: "codex.command.mcpSettings",
    descriptionIntlId: "codex.commandDescription.mcpSettings",
    commandMenuGroupKey: "configure",
    commandMenu: true,
  },
  {
    id: "personalitySettings",
    titleIntlId: "codex.command.personalitySettings",
    descriptionIntlId: "codex.commandDescription.personalitySettings",
    commandMenuGroupKey: "configure",
    commandMenu: true,
  },
  {
    id: "keyboardShortcuts",
    titleIntlId: "codex.command.keyboardShortcuts",
    descriptionIntlId: "codex.commandDescription.keyboardShortcuts",
    commandMenuGroupKey: "configure",
    commandMenu: true,
  },
  {
    id: "showKeyboardShortcuts",
    titleIntlId: "codex.command.showKeyboardShortcuts",
    descriptionIntlId: "codex.commandDescription.showKeyboardShortcuts",
    availableIn: ["electron"],
    shortcutScope: "app",
    electron: {
      menuTitle: "Keyboard Shortcuts",
      menuTitleIntlId: "codex.commandMenuTitle.showKeyboardShortcuts",
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+/" }],
    },
  },
  {
    id: "manageTasks",
    titleIntlId: "codex.command.manageTasks",
    descriptionIntlId: "codex.commandDescription.manageTasks",
    commandMenuGroupKey: "app",
    commandMenu: true,
  },
  {
    id: "openProcessManager",
    titleIntlId: "codex.command.openProcessManager",
    descriptionIntlId: "codex.commandDescription.openProcessManager",
    availableIn: ["electron"],
    shortcutScope: "app",
    commandMenuGroupKey: "app",
    commandMenu: true,
    electron: {
      menuTitle: "Process Manager",
      menuTitleIntlId: "codex.commandMenuTitle.openProcessManager",
      defaultKeybindings: [{ key: "Ctrl+Alt+M" }],
    },
  },
  {
    id: "forceReloadSkills",
    titleIntlId: "codex.command.forceReloadSkills",
    descriptionIntlId: "codex.commandDescription.forceReloadSkills",
    commandMenuGroupKey: "skills",
    commandMenu: true,
  },
  {
    id: "installPrimaryRuntime",
    titleIntlId: "codex.command.installPrimaryRuntime",
    descriptionIntlId: "codex.commandDescription.installPrimaryRuntime",
    commandMenuGroupKey: "configure",
    commandMenu: true,
  },
  {
    id: "openSkills",
    titleIntlId: "codex.command.openSkills",
    descriptionIntlId: "codex.commandDescription.openSkills",
    commandMenuGroupKey: "skills",
    commandMenu: true,
  },
  {
    id: "openFolder",
    titleIntlId: "codex.command.openFolder",
    descriptionIntlId: "codex.commandDescription.openFolder",
    commandMenuGroupKey: "workspace",
    commandMenu: true,
    electron: {
      menuTitle: "Open Folder…",
      menuTitleIntlId: "codex.commandMenuTitle.openFolder",
      defaultKeybindings: [{ key: "CmdOrCtrl+O" }],
    },
  },
  {
    id: "toggleSidebar",
    titleIntlId: "codex.command.toggleSidebar",
    descriptionIntlId: "codex.commandDescription.toggleSidebar",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Toggle Sidebar",
      menuTitleIntlId: "codex.commandMenuTitle.toggleSidebar",
      defaultKeybindings: [{ key: "CmdOrCtrl+B" }],
    },
  },
  {
    id: "toggleBottomPanel",
    titleIntlId: "codex.command.toggleBottomPanel",
    descriptionIntlId: "codex.commandDescription.toggleBottomPanel",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Toggle Bottom Panel",
      menuTitleIntlId: "codex.commandMenuTitle.toggleBottomPanel",
      defaultKeybindings: [{ key: "CmdOrCtrl+J" }],
    },
  },
  {
    id: "toggleTerminal",
    titleIntlId: "codex.command.toggleTerminal",
    descriptionIntlId: "codex.commandDescription.toggleTerminal",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Open Terminal",
      menuTitleIntlId: "codex.commandMenuTitle.toggleTerminal",
      defaultKeybindings: [{ key: "Control+`" }],
    },
  },
  {
    id: "openBrowserTab",
    titleIntlId: "codex.command.openBrowserTab",
    descriptionIntlId: "codex.commandDescription.openBrowserTab",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Open Browser Tab",
      menuTitleIntlId: "codex.commandMenuTitle.openBrowserTab",
      defaultKeybindings: [{ key: "CmdOrCtrl+T" }],
    },
  },
  {
    id: "toggleBrowserPanel",
    titleIntlId: "codex.command.toggleBrowserPanel",
    descriptionIntlId: "codex.commandDescription.toggleBrowserPanel",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Toggle Browser Panel",
      menuTitleIntlId: "codex.commandMenuTitle.toggleBrowserPanel",
      defaultKeybindings: [{ key: "CmdOrCtrl+Shift+B" }],
    },
  },
  {
    id: "openReviewTab",
    titleIntlId: "codex.command.openReviewTab",
    descriptionIntlId: "codex.commandDescription.openReviewTab",
    availableIn: ["electron", "browser"],
    shortcutScope: "app",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      defaultKeybindings: [{ key: "Ctrl+Shift+G" }],
    },
  },
  {
    id: "toggleSidePanel",
    titleIntlId: "codex.command.toggleSidePanel",
    descriptionIntlId: "codex.commandDescription.toggleSidePanel",
    commandMenuGroupKey: "panels",
    commandMenu: true,
    electron: {
      menuTitle: "Toggle Side Panel",
      menuTitleIntlId: "codex.commandMenuTitle.toggleSidePanel",
      defaultKeybindings: [{ key: "CmdOrCtrl+Alt+B" }],
    },
  },
  {
    id: "toggleMaximizeSidePanel",
    titleIntlId: "codex.command.toggleMaximizeSidePanel",
    descriptionIntlId: "codex.commandDescription.toggleMaximizeSidePanel",
    shortcutScope: "app",
  },
  {
    id: "findInThread",
    titleIntlId: "codex.command.findInThread",
    descriptionIntlId: "codex.commandDescription.findInThread",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Find",
      menuTitleIntlId: "codex.commandMenuTitle.findInThread",
      defaultKeybindings: [{ key: "CmdOrCtrl+F" }],
      platformDefaultKeybindings: {
        macOS: [{ key: "Command+F" }],
        default: [{ key: "Ctrl+F" }],
      },
    },
  },
  {
    id: "focusBrowserAddressBar",
    titleIntlId: "codex.command.focusBrowserAddressBar",
    descriptionIntlId: "codex.commandDescription.focusBrowserAddressBar",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Focus Browser Address Bar",
      menuTitleIntlId: "codex.commandMenuTitle.focusBrowserAddressBar",
      defaultKeybindings: [{ key: "CmdOrCtrl+L" }],
    },
  },
  {
    id: "navigateBrowserBack",
    titleIntlId: "codex.command.navigateBrowserBack",
    descriptionIntlId: "codex.commandDescription.navigateBrowserBack",
    availableIn: ["electron"],
    shortcutScope: "app",
    electron: {
      platformDefaultKeybindings: {
        macOS: [{ key: "Command+Left" }],
        default: [{ key: "Alt+Left" }],
      },
    },
  },
  {
    id: "navigateBrowserForward",
    titleIntlId: "codex.command.navigateBrowserForward",
    descriptionIntlId: "codex.commandDescription.navigateBrowserForward",
    availableIn: ["electron"],
    shortcutScope: "app",
    electron: {
      platformDefaultKeybindings: {
        macOS: [{ key: "Command+Right" }],
        default: [{ key: "Alt+Right" }],
      },
    },
  },
  {
    id: "navigateBack",
    titleIntlId: "codex.command.navigateBack",
    descriptionIntlId: "codex.commandDescription.navigateBack",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Back",
      menuTitleIntlId: "codex.commandMenuTitle.navigateBack",
      defaultKeybindings: [{ key: "CmdOrCtrl+[" }, { key: "MouseBack" }],
    },
  },
  {
    id: "navigateForward",
    titleIntlId: "codex.command.navigateForward",
    descriptionIntlId: "codex.commandDescription.navigateForward",
    commandMenuGroupKey: "navigation",
    commandMenu: true,
    electron: {
      menuTitle: "Forward",
      menuTitleIntlId: "codex.commandMenuTitle.navigateForward",
      defaultKeybindings: [{ key: "CmdOrCtrl+]" }, { key: "MouseForward" }],
    },
  },
  {
    id: "logOut",
    titleIntlId: "codex.command.logOut",
    descriptionIntlId: "codex.commandDescription.logOut",
    commandMenuGroupKey: "app",
    commandMenu: true,
  },
  {
    id: "feedback",
    titleIntlId: "codex.command.feedback",
    descriptionIntlId: "codex.commandDescription.feedback",
    commandMenuGroupKey: "app",
    commandMenu: true,
  },
  {
    id: "environmentAction1",
    titleIntlId: "codex.command.environmentAction1",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
    electron: {
      defaultKeybindings: [{ key: "Command+Shift+D" }],
    },
  },
  {
    id: "environmentAction2",
    titleIntlId: "codex.command.environmentAction2",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction3",
    titleIntlId: "codex.command.environmentAction3",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction4",
    titleIntlId: "codex.command.environmentAction4",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction5",
    titleIntlId: "codex.command.environmentAction5",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction6",
    titleIntlId: "codex.command.environmentAction6",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction7",
    titleIntlId: "codex.command.environmentAction7",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction8",
    titleIntlId: "codex.command.environmentAction8",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "environmentAction9",
    titleIntlId: "codex.command.environmentAction9",
    descriptionIntlId: "codex.commandDescription.environmentActionSlot",
    shortcutScope: "app",
    commandMenuGroupKey: "workspace",
  },
  {
    id: "thread1",
    titleIntlId: "codex.command.thread1",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 1",
      menuTitleIntlId: "codex.commandMenuTitle.thread1",
      defaultKeybindings: [{ key: "CmdOrCtrl+1" }],
    },
  },
  {
    id: "thread2",
    titleIntlId: "codex.command.thread2",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 2",
      menuTitleIntlId: "codex.commandMenuTitle.thread2",
      defaultKeybindings: [{ key: "CmdOrCtrl+2" }],
    },
  },
  {
    id: "thread3",
    titleIntlId: "codex.command.thread3",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 3",
      menuTitleIntlId: "codex.commandMenuTitle.thread3",
      defaultKeybindings: [{ key: "CmdOrCtrl+3" }],
    },
  },
  {
    id: "thread4",
    titleIntlId: "codex.command.thread4",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 4",
      menuTitleIntlId: "codex.commandMenuTitle.thread4",
      defaultKeybindings: [{ key: "CmdOrCtrl+4" }],
    },
  },
  {
    id: "thread5",
    titleIntlId: "codex.command.thread5",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 5",
      menuTitleIntlId: "codex.commandMenuTitle.thread5",
      defaultKeybindings: [{ key: "CmdOrCtrl+5" }],
    },
  },
  {
    id: "thread6",
    titleIntlId: "codex.command.thread6",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 6",
      menuTitleIntlId: "codex.commandMenuTitle.thread6",
      defaultKeybindings: [{ key: "CmdOrCtrl+6" }],
    },
  },
  {
    id: "thread7",
    titleIntlId: "codex.command.thread7",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 7",
      menuTitleIntlId: "codex.commandMenuTitle.thread7",
      defaultKeybindings: [{ key: "CmdOrCtrl+7" }],
    },
  },
  {
    id: "thread8",
    titleIntlId: "codex.command.thread8",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 8",
      menuTitleIntlId: "codex.commandMenuTitle.thread8",
      defaultKeybindings: [{ key: "CmdOrCtrl+8" }],
    },
  },
  {
    id: "thread9",
    titleIntlId: "codex.command.thread9",
    descriptionIntlId: "codex.commandDescription.threadSlot",
    electron: {
      menuTitle: "Go to Chat 9",
      menuTitleIntlId: "codex.commandMenuTitle.thread9",
      defaultKeybindings: [{ key: "CmdOrCtrl+9" }],
    },
  },
];
