// Restored from ref/webview/assets/isArrayLikeObject-1Hrr5Oll.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 45 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const A: any;
export declare const B: any;
export declare const C: any;
export declare const D: any;
export declare const E: any;
export declare const F: any;
export declare const G: any;
export declare const H: any;
export declare const I: any;
export declare const L: any;
export declare const M: any;
export declare const N: any;
export declare const O: any;
export declare const P: any;
export declare const R: any;
export declare const S: any;
export declare const T: any;
export declare const U: any;
export declare const V: any;
export declare const W: any;
export declare const _: any;
export declare const a: any;
export declare const b: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const j: any;
export declare const k: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
export declare const v: any;
export declare const w: any;
export declare const x: any;
export declare const y: any;
export declare const z: any;

// Aliases used by consumer checkpoints
export declare const isArrayLikeObjectA: any;
export declare const isArrayLikeObjectB: any;
export declare const isArrayLikeObjectC: any;
export declare const isArrayLikeObjectD: any;
export declare const isArrayLikeObjectE: any;
export declare const isArrayLikeObjectF: any;
export declare const isArrayLikeObjectG: any;
export declare const isArrayLikeObjectH: any;
export declare const isArrayLikeObjectI: any;
export declare const isArrayLikeObjectJ: any;
export declare const isArrayLikeObjectK: any;
export declare const isArrayLikeObjectL: any;
export declare const isArrayLikeObjectM: any;
export declare const isArrayLikeObjectN: any;
export declare const isArrayLikeObjectO: any;
export declare const isArrayLikeObjectP: any;
export declare const isArrayLikeObjectR: any;
export declare const isArrayLikeObjectS: any;
export declare const isArrayLikeObjectT: any;
export declare const isArrayLikeObjectU: any;
export declare const isArrayLikeObjectUnderscore: any;
export declare const isArrayLikeObjectV: any;
export declare const isArrayLikeObjectW: any;
export declare const isArrayLikeObjectX: any;
export declare const isArrayLikeObjectY: any;
export declare const isArrayLikeObjectZ: any;

// Additional aliases exported for consumers mapped via IMPORT_MAP
export const _isArrayLikeObjectP: any = undefined;
export const _isArrayLikeObjectS: any = undefined;
export const _isArrayLikeObjectI: any = undefined;
export const _isArrayLikeObjectR: any = undefined;
export const _isArrayLikeObjectN: any = undefined;
export const _isArrayLikeObjectT: any = undefined;
export const _isArrayLikeObjectA: any = undefined;
export const _isArrayLikeObjectB: any = undefined;
export const _isArrayLikeObjectC: any = undefined;
export const _isArrayLikeObjectD: any = undefined;
export const _isArrayLikeObjectF: any = undefined;
export const _isArrayLikeObjectG: any = undefined;
export const _isArrayLikeObjectH: any = undefined;
export const _isArrayLikeObjectL: any = undefined;
export const _isArrayLikeObjectM: any = undefined;
export const _isArrayLikeObjectO: any = undefined;
export const _isArrayLikeObjectU: any = undefined;
export const _isArrayLikeObjectV: any = undefined;
export const _isArrayLikeObjectW: any = undefined;
