// Restored from ref/webview/assets/merge-Ch0yXQoh.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 17 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const _: any;
export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const mergeA: any;
export declare const mergeC: any;
export declare const mergeD: any;
export declare const mergeF: any;
export declare const mergeG: any;
export declare const mergeH: any;
export declare const mergeI: any;
export declare const mergeL: any;
export declare const mergeM: any;
export declare const mergeN: any;
export declare const mergeO: any;
export declare const mergeP: any;
export declare const mergeR: any;
export declare const mergeS: any;
export declare const mergeT: any;
export declare const mergeU: any;
export declare const mergeUnderscore: any;
