// Restored from ref/webview/assets/reduce-C4fu3kBc.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 26 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const C: any;
export declare const E: any;
export declare const S: any;
export declare const T: any;
export declare const _: any;
export declare const a: any;
export declare const b: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
export declare const v: any;
export declare const w: any;
export declare const x: any;
export declare const y: any;

// Aliases used by consumer checkpoints
export declare const reduceA: any;
export declare const reduceB: any;
export declare const reduceC: any;
export declare const reduceD: any;
export declare const reduceE: any;
export declare const reduceF: any;
export declare const reduceG: any;
export declare const reduceH: any;
export declare const reduceI: any;
export declare const reduceL: any;
export declare const reduceM: any;
export declare const reduceN: any;
export declare const reduceO: any;
export declare const reduceP: any;
export declare const reduceR: any;
export declare const reduceS: any;
export declare const reduceT: any;
export declare const reduceU: any;
export declare const reduceUnderscore: any;
export declare const reduceV: any;
export declare const reduceW: any;
export declare const reduceX: any;
export declare const reduceY: any;
