// Restored from ref/webview/assets/vscode-api-Cc4BqLmp.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 31 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const A: any;
export declare const C: any;
export declare const D: any;
export declare const E: any;
export declare const O: any;
export declare const S: any;
export declare const T: any;
export declare const _: any;
export declare const a: any;
export declare const b: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const j: any;
export declare const k: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;
export declare const v: any;
export declare const w: any;
export declare const x: any;
export declare const y: any;

// Aliases used by consumer checkpoints
export declare const vscodeApiA: any;
export declare const vscodeApiC: any;
export declare const vscodeApiD: any;
export declare const vscodeApiF: any;
export declare const vscodeApiG: any;
export declare const vscodeApiH: any;
export declare const vscodeApiI: any;
export declare const vscodeApiJ: any;
export declare const vscodeApiK: any;
export declare const vscodeApiL: any;
export declare const vscodeApiM: any;
export declare const vscodeApiN: any;
export declare const vscodeApiO: any;
export declare const vscodeApiP: any;
export declare const vscodeApiR: any;
export declare const vscodeApiS: any;
export declare const vscodeApiT: any;
export declare const vscodeApiU: any;
export declare const vscodeApiUnderscore: any;
export declare const vscodeApiV: any;

// Additional aliases exported for consumers mapped via IMPORT_MAP
export const automationScheduleImport2: any = undefined;
export const automationScheduleImport3: any = undefined;
export const commandKeybindingsImport4: any = undefined;
export const commandKeybindingsImport5: any = undefined;
export const parseDirectivesImport1: any = undefined;
