// Restored from ref/webview/assets/chunk-4TB4RGXK-B3SUDt4C.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 4 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const i: any;
export declare const n: any;
export declare const r: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunk4TB4RGXKI: any;
export declare const chunk4TB4RGXKN: any;
export declare const chunk4TB4RGXKR: any;
export declare const chunk4TB4RGXKT: any;
