// Restored from ref/webview/assets/chunk-JZLCHNYA-HNai7LB6.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 10 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const chunkJZLCHNYAA: any;
export declare const chunkJZLCHNYAC: any;
export declare const chunkJZLCHNYAI: any;
export declare const chunkJZLCHNYAL: any;
export declare const chunkJZLCHNYAN: any;
export declare const chunkJZLCHNYAO: any;
export declare const chunkJZLCHNYAR: any;
export declare const chunkJZLCHNYAS: any;
export declare const chunkJZLCHNYAT: any;
export declare const chunkJZLCHNYAU: any;
