// Restored from ref/webview/assets/chunk-QXUST7PY-B8nc5wSD.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 5 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const i: any;
export declare const n: any;
export declare const r: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkQXUST7PYA: any;
export declare const chunkQXUST7PYI: any;
export declare const chunkQXUST7PYN: any;
export declare const chunkQXUST7PYR: any;
export declare const chunkQXUST7PYT: any;
