// Restored from ref/webview/assets/chunk-FPAJGGOC-Cy-1bcKF.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 16 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const chunkFPAJGGOCA: any;
export declare const chunkFPAJGGOCC: any;
export declare const chunkFPAJGGOCD: any;
export declare const chunkFPAJGGOCF: any;
export declare const chunkFPAJGGOCG: any;
export declare const chunkFPAJGGOCH: any;
export declare const chunkFPAJGGOCI: any;
export declare const chunkFPAJGGOCL: any;
export declare const chunkFPAJGGOCM: any;
export declare const chunkFPAJGGOCN: any;
export declare const chunkFPAJGGOCO: any;
export declare const chunkFPAJGGOCP: any;
export declare const chunkFPAJGGOCR: any;
export declare const chunkFPAJGGOCS: any;
export declare const chunkFPAJGGOCT: any;
export declare const chunkFPAJGGOCU: any;
