// Restored from ref/webview/assets/chunk-5FUZZQ4R-B4cKsdW4.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 10 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const a: any;
export declare const c: any;
export declare const i: any;
export declare const l: any;
export declare const n: any;
export declare const o: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const chunk5FUZZQ4RA: any;
export declare const chunk5FUZZQ4RC: any;
export declare const chunk5FUZZQ4RI: any;
export declare const chunk5FUZZQ4RL: any;
export declare const chunk5FUZZQ4RN: any;
export declare const chunk5FUZZQ4RO: any;
export declare const chunk5FUZZQ4RR: any;
export declare const chunk5FUZZQ4RS: any;
export declare const chunk5FUZZQ4RT: any;
export declare const chunk5FUZZQ4RU: any;
