// Restored from ref/webview/assets/chunk-S3R3BYOJ-B7UcUgIb.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 17 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const _: any;
export declare const a: any;
export declare const c: any;
export declare const d: any;
export declare const f: any;
export declare const g: any;
export declare const h: any;
export declare const i: any;
export declare const l: any;
export declare const m: any;
export declare const n: any;
export declare const o: any;
export declare const p: any;
export declare const r: any;
export declare const s: any;
export declare const t: any;
export declare const u: any;

// Aliases used by consumer checkpoints
export declare const chunkS3R3BYOJA: any;
export declare const chunkS3R3BYOJC: any;
export declare const chunkS3R3BYOJD: any;
export declare const chunkS3R3BYOJF: any;
export declare const chunkS3R3BYOJG: any;
export declare const chunkS3R3BYOJH: any;
export declare const chunkS3R3BYOJI: any;
export declare const chunkS3R3BYOJL: any;
export declare const chunkS3R3BYOJM: any;
export declare const chunkS3R3BYOJN: any;
export declare const chunkS3R3BYOJO: any;
export declare const chunkS3R3BYOJP: any;
export declare const chunkS3R3BYOJR: any;
export declare const chunkS3R3BYOJS: any;
export declare const chunkS3R3BYOJT: any;
export declare const chunkS3R3BYOJU: any;
export declare const chunkS3R3BYOJUnderscore: any;
