// Restored from ref/webview/assets/chunk-N4CR4FBY-ClZLl4Py.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 3 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */

export declare const n: any;
export declare const r: any;
export declare const t: any;

// Aliases used by consumer checkpoints
export declare const chunkN4CR4FBYN: any;
export declare const chunkN4CR4FBYR: any;
export declare const chunkN4CR4FBYT: any;
